services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - ventprom-network

  web:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    networks:
      - ventprom-network

networks:
  ventprom-network:
    driver: bridge