services:
  api:
    image: ${DOCKER_USERNAME}/ventprom-api:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    restart: always

  web:
    image: ${DOCKER_USERNAME}/ventprom-web:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - api
    restart: always
