version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.workspace
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    volumes:
      - ./packages:/app/packages
      - ./apps:/app/apps
    command: ["sh", "-c", "cd apps/api && npm start"]

  web:
    build:
      context: .
      dockerfile: Dockerfile.workspace
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./packages:/app/packages
      - ./apps:/app/apps
    command: ["sh", "-c", "cd apps/web && npm start"]

  # Alternative: single container with both services
  app:
    build:
      context: .
      dockerfile: Dockerfile.workspace
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV=production
    volumes:
      - ./packages:/app/packages
      - ./apps:/app/apps
    command: ["sh", "-c", "cd apps/api && npm start & cd apps/web && npm start & wait"]
