services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.quick
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    volumes:
      - ./packages/parsers/dist:/app/packages/parsers/dist:ro

  web:
    build:
      context: .
      dockerfile: Dockerfile.quick
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - api
    volumes:
      - ./packages/parsers/dist:/app/packages/parsers/dist:ro

